// <auto-generated />
using Infrastructure.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Core.Entities.Contato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DDD")
                        .HasMaxLength(2)
                        .HasColumnType("INT");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR(100)");

                    b.Property<int>("Telefone")
                        .HasMaxLength(9)
                        .HasColumnType("INT");

                    b.HasKey("Id");

                    b.HasIndex("DDD");

                    b.ToTable("Contato", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Regioes", b =>
                {
                    b.Property<int>("DDD")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2)
                        .HasColumnType("INT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DDD"));

                    b.Property<string>("Regiao")
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR(20)");

                    b.Property<string>("UF")
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR(20)");

                    b.HasKey("DDD");

                    b.ToTable("Regioes", (string)null);

                    b.HasData(
                        new
                        {
                            DDD = 11,
                            Regiao = "Sudeste",
                            UF = "SP"
                        },
                        new
                        {
                            DDD = 12,
                            Regiao = "Sudeste",
                            UF = "SP"
                        },
                        new
                        {
                            DDD = 13,
                            Regiao = "Sudeste",
                            UF = "SP"
                        },
                        new
                        {
                            DDD = 14,
                            Regiao = "Sudeste",
                            UF = "SP"
                        },
                        new
                        {
                            DDD = 15,
                            Regiao = "Sudeste",
                            UF = "SP"
                        },
                        new
                        {
                            DDD = 16,
                            Regiao = "Sudeste",
                            UF = "SP"
                        },
                        new
                        {
                            DDD = 17,
                            Regiao = "Sudeste",
                            UF = "SP"
                        },
                        new
                        {
                            DDD = 18,
                            Regiao = "Sudeste",
                            UF = "SP"
                        },
                        new
                        {
                            DDD = 19,
                            Regiao = "Sudeste",
                            UF = "SP"
                        },
                        new
                        {
                            DDD = 21,
                            Regiao = "Sudeste",
                            UF = "RJ"
                        },
                        new
                        {
                            DDD = 22,
                            Regiao = "Sudeste",
                            UF = "RJ"
                        },
                        new
                        {
                            DDD = 24,
                            Regiao = "Sudeste",
                            UF = "RJ"
                        },
                        new
                        {
                            DDD = 27,
                            Regiao = "Sudeste",
                            UF = "ES"
                        },
                        new
                        {
                            DDD = 28,
                            Regiao = "Sudeste",
                            UF = "ES"
                        },
                        new
                        {
                            DDD = 31,
                            Regiao = "Sudeste",
                            UF = "MG"
                        },
                        new
                        {
                            DDD = 32,
                            Regiao = "Sudeste",
                            UF = "MG"
                        },
                        new
                        {
                            DDD = 33,
                            Regiao = "Sudeste",
                            UF = "MG"
                        },
                        new
                        {
                            DDD = 34,
                            Regiao = "Sudeste",
                            UF = "MG"
                        },
                        new
                        {
                            DDD = 35,
                            Regiao = "Sudeste",
                            UF = "MG"
                        },
                        new
                        {
                            DDD = 37,
                            Regiao = "Sudeste",
                            UF = "MG"
                        },
                        new
                        {
                            DDD = 41,
                            Regiao = "Sul",
                            UF = "PR"
                        },
                        new
                        {
                            DDD = 42,
                            Regiao = "Sul",
                            UF = "SC"
                        },
                        new
                        {
                            DDD = 43,
                            Regiao = "Sul",
                            UF = "RS"
                        },
                        new
                        {
                            DDD = 44,
                            Regiao = "Centro-Oeste",
                            UF = "PR"
                        },
                        new
                        {
                            DDD = 45,
                            Regiao = "Centro-Oeste",
                            UF = "PR"
                        },
                        new
                        {
                            DDD = 46,
                            Regiao = "Centro-Oeste",
                            UF = "PR"
                        },
                        new
                        {
                            DDD = 47,
                            Regiao = "Sul",
                            UF = "SC"
                        },
                        new
                        {
                            DDD = 48,
                            Regiao = "Sul",
                            UF = "SC"
                        },
                        new
                        {
                            DDD = 49,
                            Regiao = "Sul",
                            UF = "SC"
                        },
                        new
                        {
                            DDD = 51,
                            Regiao = "Sul",
                            UF = "RS"
                        },
                        new
                        {
                            DDD = 52,
                            Regiao = "Centro-Oeste",
                            UF = "MS"
                        },
                        new
                        {
                            DDD = 53,
                            Regiao = "Centro-Oeste",
                            UF = "MS"
                        },
                        new
                        {
                            DDD = 61,
                            Regiao = "Centro-Oeste",
                            UF = "DF"
                        },
                        new
                        {
                            DDD = 62,
                            Regiao = "Centro-Oeste",
                            UF = "GO"
                        },
                        new
                        {
                            DDD = 63,
                            Regiao = "Centro-Oeste",
                            UF = "TO"
                        },
                        new
                        {
                            DDD = 64,
                            Regiao = "Nordeste",
                            UF = "TO"
                        },
                        new
                        {
                            DDD = 65,
                            Regiao = "Centro-Oeste",
                            UF = "MT"
                        },
                        new
                        {
                            DDD = 66,
                            Regiao = "Centro-Oeste",
                            UF = "MT"
                        },
                        new
                        {
                            DDD = 67,
                            Regiao = "Centro-Oeste",
                            UF = "MS"
                        },
                        new
                        {
                            DDD = 68,
                            Regiao = "Norte",
                            UF = "AC"
                        },
                        new
                        {
                            DDD = 69,
                            Regiao = "Norte",
                            UF = "AM"
                        },
                        new
                        {
                            DDD = 71,
                            Regiao = "Nordeste",
                            UF = "BA"
                        },
                        new
                        {
                            DDD = 73,
                            Regiao = "Nordeste",
                            UF = "BA"
                        },
                        new
                        {
                            DDD = 74,
                            Regiao = "Nordeste",
                            UF = "PA"
                        },
                        new
                        {
                            DDD = 75,
                            Regiao = "Nordeste",
                            UF = "BA"
                        },
                        new
                        {
                            DDD = 77,
                            Regiao = "Nordeste",
                            UF = "BA"
                        },
                        new
                        {
                            DDD = 79,
                            Regiao = "Nordeste",
                            UF = "SE"
                        },
                        new
                        {
                            DDD = 81,
                            Regiao = "Nordeste",
                            UF = "PE"
                        },
                        new
                        {
                            DDD = 82,
                            Regiao = "Nordeste",
                            UF = "AL"
                        },
                        new
                        {
                            DDD = 83,
                            Regiao = "Nordeste",
                            UF = "PB"
                        },
                        new
                        {
                            DDD = 84,
                            Regiao = "Nordeste",
                            UF = "RN"
                        },
                        new
                        {
                            DDD = 85,
                            Regiao = "Nordeste",
                            UF = "CE"
                        },
                        new
                        {
                            DDD = 86,
                            Regiao = "Nordeste",
                            UF = "PI"
                        },
                        new
                        {
                            DDD = 87,
                            Regiao = "Nordeste",
                            UF = "PE"
                        },
                        new
                        {
                            DDD = 88,
                            Regiao = "Nordeste",
                            UF = "CE"
                        },
                        new
                        {
                            DDD = 89,
                            Regiao = "Nordeste",
                            UF = "PI"
                        },
                        new
                        {
                            DDD = 91,
                            Regiao = "Norte",
                            UF = "PA"
                        },
                        new
                        {
                            DDD = 92,
                            Regiao = "Norte",
                            UF = "AM"
                        },
                        new
                        {
                            DDD = 93,
                            Regiao = "Norte",
                            UF = "PA"
                        },
                        new
                        {
                            DDD = 94,
                            Regiao = "Norte",
                            UF = "PA"
                        },
                        new
                        {
                            DDD = 95,
                            Regiao = "Norte",
                            UF = "RR"
                        },
                        new
                        {
                            DDD = 96,
                            Regiao = "Norte",
                            UF = "AP"
                        },
                        new
                        {
                            DDD = 97,
                            Regiao = "Norte",
                            UF = "AM"
                        },
                        new
                        {
                            DDD = 98,
                            Regiao = "Nordeste",
                            UF = "MA"
                        },
                        new
                        {
                            DDD = 99,
                            Regiao = "Nordeste",
                            UF = "MA"
                        });
                });

            modelBuilder.Entity("Core.Entities.Contato", b =>
                {
                    b.HasOne("Core.Entities.Regioes", "Regiao")
                        .WithMany()
                        .HasForeignKey("DDD")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Regiao");
                });
#pragma warning restore 612, 618
        }
    }
}
